version: "3.8"
services:
  calibre-web:
    build: .
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/calibre/books:/books
      - /opt/calibre/config:/config
      - ./scripts:/scripts
      - /mnt/calibre/newbooks2:/newbooks
    ports:
      - 8083:8083
    restart: unless-stopped
